// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACd0ASpagjgccrgqcFKcB740LYlcSE-qQ',
    appId: '1:1026841261942:web:d08cf54f60a44d0a752c57',
    messagingSenderId: '1026841261942',
    projectId: 'cumulosoaring',
    authDomain: 'cumulosoaring.firebaseapp.com',
    databaseURL: 'https://cumulosoaring-default-rtdb.firebaseio.com',
    storageBucket: 'cumulosoaring.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0OsIA1eStOxlxpY6Kt4ffBI6VmjldNLY',
    appId: '1:1026841261942:android:6d68145516c2350b752c57',
    messagingSenderId: '1026841261942',
    projectId: 'cumulosoaring',
    databaseURL: 'https://cumulosoaring-default-rtdb.firebaseio.com',
    storageBucket: 'cumulosoaring.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx3o0r4HUo_telBkuorMZnduDzqife7dQ',
    appId: '1:1026841261942:ios:1321da9d3ed95de5752c57',
    messagingSenderId: '1026841261942',
    projectId: 'cumulosoaring',
    databaseURL: 'https://cumulosoaring-default-rtdb.firebaseio.com',
    storageBucket: 'cumulosoaring.appspot.com',
    iosClientId: '1026841261942-3c2c3a0sr4sgbvushqa7f9e6t3vtg25s.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx3o0r4HUo_telBkuorMZnduDzqife7dQ',
    appId: '1:1026841261942:ios:1321da9d3ed95de5752c57',
    messagingSenderId: '1026841261942',
    projectId: 'cumulosoaring',
    databaseURL: 'https://cumulosoaring-default-rtdb.firebaseio.com',
    storageBucket: 'cumulosoaring.appspot.com',
    iosClientId: '1026841261942-3c2c3a0sr4sgbvushqa7f9e6t3vtg25s.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACd0ASpagjgccrgqcFKcB740LYlcSE-qQ',
    appId: '1:1026841261942:web:abf30a2150297e79752c57',
    messagingSenderId: '1026841261942',
    projectId: 'cumulosoaring',
    authDomain: 'cumulosoaring.firebaseapp.com',
    databaseURL: 'https://cumulosoaring-default-rtdb.firebaseio.com',
    storageBucket: 'cumulosoaring.appspot.com',
  );
}
